CREATE TABLE Persona (
  id_persona VARCHAR(20) NOT NULL PRIMARY KEY,
  nombre VARCHAR(50) NOT NULL,
  genero VARCHAR(30) NOT NULL,
  edad INTEGER,
  direccion VARCHAR(150) NOT NULL,
  telefono VARCHAR(20)
);

-- Enumeración para el genero
CREATE TYPE EGenero AS ENUM ('MASCULINO', 'FEMENINO', 'OTRO');


CREATE TABLE cliente (
  id_cliente BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  contrasena VARCHAR(60) NOT NULL,
  estado VARCHAR(5) NOT NULL,
  id_persona VARCHAR(20) NOT NULL,
  CONSTRAINT fk_cliente_persona FOREIGN KEY (id_persona) REFERENCES Persona(id_persona)
);

CREATE TABLE cuenta (
  nro_cuenta VARCHAR(35) PRIMARY KEY,
  tipo_cuenta VARCHAR(25) NOT NULL,
  saldo_inicial DECIMAL(19,2) NOT NULL,
  estado VARCHAR(20) NOT NULL,
  id_cliente BIGINT NOT NULL,
  CONSTRAINT fk_cuenta_cliente FOREIGN KEY (id_cliente) REFERENCES Cliente(id_cliente)
);

CREATE TABLE movimiento (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nro_cuenta VARCHAR(35) NOT NULL,
  fecha DATE NOT NULL,
  tipo_movimiento VARCHAR(25) NOT NULL,
  monto DECIMAL(19,2) NOT NULL,
  saldo DECIMAL(19,2) NOT NULL,
  descripcion VARCHAR(135),
  CONSTRAINT fk_movimiento_cuenta FOREIGN KEY (nro_cuenta) REFERENCES Cuenta(nro_cuenta)
);
